Feat/select star
vanilladb/vanillacore pull request #107
Opened 2023-03-15 01:26 UTC by wilbertharriman

2023-03-17 09:09 UTC, SLMT requested changes
You can try to make `*` viewed as one of fields in `Parser` and then replace it with all fields in `Verifier`.

2023-04-16 10:08 UTC, wilbertharriman commented
1. Added suggested changes in `Parser` and `Verifier`
2. Use `ServerInit.loadTestbed()` for SELECT * integration test
3. Remove macOS from github actions. Otherwise, the limit on running github actions could be reached easily. When the limit is reached, github runners will not start and CI actions will fail after 6 hours.

2023-04-16 14:05 UTC, SLMT requested changes
Great improvement! `SELECT * ...` is an important syntax sugar for DB users. I think it is good to go once some my tiny requests are addressed.

2023-04-16 14:05 UTC, SLMT commented on src/main/java/org/vanilladb/core/query/planner/Verifier.java
> +			if (fldName.equals("*")) {
I think there should also be a constant for the wildcard in this class like how we did in `Lexer`.

2023-04-17 05:26 UTC, wilbertharriman commented on src/main/java/org/vanilladb/core/query/parse/Lexer.java
> +	public static final String WILDCARD = "*";
WILDCARD is now a static and final field

2023-04-17 05:26 UTC, wilbertharriman commented on src/main/java/org/vanilladb/core/query/planner/Verifier.java
> +import static org.vanilladb.core.query.parse.Lexer.WILDCARD;
import WILDCARD from `Lexer`

2023-04-30 06:22 UTC, SLMT approved these changes
Good to go!

2023-04-30 06:40 UTC, merged